<?php
/**
 * AUTOGENERATED CONTENT - DO NOT EDIT!
 * ALL CHANGES WILL BE UNDONE!
 * RUN `./scripts/generate-sprites` TO UPDATE THIS FILE
 *
 * @package PhpMyAdmin-theme
 */

/**
 * Returns map of sprites inside sprite.png
 *
 * @return array Data of sprites
 */
function PMA_sprites()
{
    return [
        'asc_order'                   => [
            'position' => '1',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_bookmark'                  => [
            'position' => '2',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_browse'                    => [
            'position' => '3',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_calendar'                  => [
            'position' => '4',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_chart'                     => [
            'position' => '5',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_close'                     => [
            'position' => '6',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_column_add'                => [
            'position' => '7',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_comment'                   => [
            'position' => '8',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_dbstatistics'              => [
            'position' => '9',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_deltbl'                    => [
            'position' => '10',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_docs'                      => [
            'position' => '11',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_docsql'                    => [
            'position' => '12',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_drop'                      => [
            'position' => '13',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_edit'                      => [
            'position' => '14',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_empty'                     => [
            'position' => '15',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_engine'                    => [
            'position' => '16',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_event_add'                 => [
            'position' => '17',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_events'                    => [
            'position' => '18',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_export'                    => [
            'position' => '19',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_favorite'                  => [
            'position' => '20',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_find_replace'              => [
            'position' => '21',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_firstpage'                 => [
            'position' => '22',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_ftext'                     => [
            'position' => '23',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_group'                     => [
            'position' => '24',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_help'                      => [
            'position' => '25',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_home'                      => [
            'position' => '26',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_import'                    => [
            'position' => '27',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_index'                     => [
            'position' => '28',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_index_add'                 => [
            'position' => '29',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_info'                      => [
            'position' => '30',
            'width'    => '11',
            'height'   => '11',
        ],
        'b_inline_edit'               => [
            'position' => '31',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_insrow'                    => [
            'position' => '32',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_lastpage'                  => [
            'position' => '33',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_minus'                     => [
            'position' => '34',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_more'                      => [
            'position' => '35',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_move'                      => [
            'position' => '36',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_newdb'                     => [
            'position' => '37',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_newtbl'                    => [
            'position' => '38',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_nextpage'                  => [
            'position' => '39',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_no_favorite'               => [
            'position' => '40',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_pdfdoc'                    => [
            'position' => '41',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_plus'                      => [
            'position' => '42',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_prevpage'                  => [
            'position' => '43',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_primary'                   => [
            'position' => '44',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_print'                     => [
            'position' => '45',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_props'                     => [
            'position' => '46',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_relations'                 => [
            'position' => '47',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_report'                    => [
            'position' => '48',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_routine_add'               => [
            'position' => '49',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_routines'                  => [
            'position' => '50',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_save'                      => [
            'position' => '51',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_saveimage'                 => [
            'position' => '52',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_sbrowse'                   => [
            'position' => '53',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_sdb'                       => [
            'position' => '54',
            'width'    => '10',
            'height'   => '10',
        ],
        'b_search'                    => [
            'position' => '55',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_selboard'                  => [
            'position' => '56',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_select'                    => [
            'position' => '57',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_snewtbl'                   => [
            'position' => '58',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_spatial'                   => [
            'position' => '59',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_sql'                       => [
            'position' => '60',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_sqldoc'                    => [
            'position' => '61',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_sqlhelp'                   => [
            'position' => '62',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_table_add'                 => [
            'position' => '63',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_tblanalyse'                => [
            'position' => '64',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_tblexport'                 => [
            'position' => '65',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_tblimport'                 => [
            'position' => '66',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_tblops'                    => [
            'position' => '67',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_tbloptimize'               => [
            'position' => '68',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_tipp'                      => [
            'position' => '69',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_trigger_add'               => [
            'position' => '70',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_triggers'                  => [
            'position' => '71',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_undo'                      => [
            'position' => '72',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_unique'                    => [
            'position' => '73',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_usradd'                    => [
            'position' => '74',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_usrcheck'                  => [
            'position' => '75',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_usrdrop'                   => [
            'position' => '76',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_usredit'                   => [
            'position' => '77',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_usrlist'                   => [
            'position' => '78',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_versions'                  => [
            'position' => '79',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_view'                      => [
            'position' => '80',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_view_add'                  => [
            'position' => '81',
            'width'    => '16',
            'height'   => '16',
        ],
        'b_views'                     => [
            'position' => '82',
            'width'    => '16',
            'height'   => '16',
        ],
        'bd_browse'                   => [
            'position' => '83',
            'width'    => '16',
            'height'   => '16',
        ],
        'bd_deltbl'                   => [
            'position' => '84',
            'width'    => '16',
            'height'   => '16',
        ],
        'bd_drop'                     => [
            'position' => '85',
            'width'    => '16',
            'height'   => '16',
        ],
        'bd_edit'                     => [
            'position' => '86',
            'width'    => '16',
            'height'   => '16',
        ],
        'bd_empty'                    => [
            'position' => '87',
            'width'    => '16',
            'height'   => '16',
        ],
        'bd_export'                   => [
            'position' => '88',
            'width'    => '16',
            'height'   => '16',
        ],
        'bd_firstpage'                => [
            'position' => '89',
            'width'    => '16',
            'height'   => '16',
        ],
        'bd_ftext'                    => [
            'position' => '90',
            'width'    => '16',
            'height'   => '16',
        ],
        'bd_index'                    => [
            'position' => '91',
            'width'    => '16',
            'height'   => '16',
        ],
        'bd_insrow'                   => [
            'position' => '92',
            'width'    => '16',
            'height'   => '16',
        ],
        'bd_lastpage'                 => [
            'position' => '93',
            'width'    => '16',
            'height'   => '16',
        ],
        'bd_nextpage'                 => [
            'position' => '94',
            'width'    => '16',
            'height'   => '16',
        ],
        'bd_prevpage'                 => [
            'position' => '95',
            'width'    => '16',
            'height'   => '16',
        ],
        'bd_primary'                  => [
            'position' => '96',
            'width'    => '16',
            'height'   => '16',
        ],
        'bd_routine_add'              => [
            'position' => '97',
            'width'    => '16',
            'height'   => '16',
        ],
        'bd_sbrowse'                  => [
            'position' => '98',
            'width'    => '16',
            'height'   => '16',
        ],
        'bd_select'                   => [
            'position' => '99',
            'width'    => '16',
            'height'   => '16',
        ],
        'bd_spatial'                  => [
            'position' => '100',
            'width'    => '16',
            'height'   => '16',
        ],
        'bd_unique'                   => [
            'position' => '101',
            'width'    => '16',
            'height'   => '16',
        ],
        'centralColumns'              => [
            'position' => '102',
            'width'    => '16',
            'height'   => '16',
        ],
        'centralColumns_add'          => [
            'position' => '103',
            'width'    => '16',
            'height'   => '16',
        ],
        'centralColumns_delete'       => [
            'position' => '104',
            'width'    => '16',
            'height'   => '16',
        ],
        'col_drop'                    => [
            'position' => '105',
            'width'    => '16',
            'height'   => '16',
        ],
        'console'                     => [
            'position' => '106',
            'width'    => '16',
            'height'   => '16',
        ],
        'database'                    => [
            'position' => '107',
            'width'    => '16',
            'height'   => '16',
        ],
        'eye'                         => [
            'position' => '108',
            'width'    => '16',
            'height'   => '16',
        ],
        'eye_grey'                    => [
            'position' => '109',
            'width'    => '16',
            'height'   => '16',
        ],
        'item'                        => [
            'position' => '110',
            'width'    => '9',
            'height'   => '9',
        ],
        'lightbulb'                   => [
            'position' => '111',
            'width'    => '16',
            'height'   => '16',
        ],
        'lightbulb_off'               => [
            'position' => '112',
            'width'    => '16',
            'height'   => '16',
        ],
        'more'                        => [
            'position' => '113',
            'width'    => '13',
            'height'   => '16',
        ],
        'new_data'                    => [
            'position' => '114',
            'width'    => '16',
            'height'   => '16',
        ],
        'new_data_hovered'            => [
            'position' => '115',
            'width'    => '16',
            'height'   => '16',
        ],
        'new_data_selected'           => [
            'position' => '116',
            'width'    => '16',
            'height'   => '16',
        ],
        'new_data_selected_hovered'   => [
            'position' => '117',
            'width'    => '16',
            'height'   => '16',
        ],
        'new_struct'                  => [
            'position' => '118',
            'width'    => '16',
            'height'   => '16',
        ],
        'new_struct_hovered'          => [
            'position' => '119',
            'width'    => '16',
            'height'   => '16',
        ],
        'new_struct_selected'         => [
            'position' => '120',
            'width'    => '16',
            'height'   => '16',
        ],
        'new_struct_selected_hovered' => [
            'position' => '121',
            'width'    => '16',
            'height'   => '16',
        ],
        'normalize'                   => [
            'position' => '122',
            'width'    => '16',
            'height'   => '16',
        ],
        'pause'                       => [
            'position' => '123',
            'width'    => '16',
            'height'   => '16',
        ],
        'php_sym'                     => [
            'position' => '124',
            'width'    => '16',
            'height'   => '16',
        ],
        'play'                        => [
            'position' => '125',
            'width'    => '16',
            'height'   => '16',
        ],
        's_asc'                       => [
            'position' => '126',
            'width'    => '16',
            'height'   => '16',
        ],
        's_asci'                      => [
            'position' => '127',
            'width'    => '16',
            'height'   => '16',
        ],
        's_attention'                 => [
            'position' => '128',
            'width'    => '16',
            'height'   => '16',
        ],
        's_cancel'                    => [
            'position' => '129',
            'width'    => '16',
            'height'   => '16',
        ],
        's_cancel2'                   => [
            'position' => '130',
            'width'    => '16',
            'height'   => '16',
        ],
        's_cog'                       => [
            'position' => '131',
            'width'    => '16',
            'height'   => '16',
        ],
        's_db'                        => [
            'position' => '132',
            'width'    => '16',
            'height'   => '16',
        ],
        's_desc'                      => [
            'position' => '133',
            'width'    => '16',
            'height'   => '16',
        ],
        's_error'                     => [
            'position' => '134',
            'width'    => '16',
            'height'   => '16',
        ],
        's_error2'                    => [
            'position' => '135',
            'width'    => '11',
            'height'   => '11',
        ],
        's_host'                      => [
            'position' => '136',
            'width'    => '16',
            'height'   => '16',
        ],
        's_info'                      => [
            'position' => '137',
            'width'    => '16',
            'height'   => '16',
        ],
        's_lang'                      => [
            'position' => '138',
            'width'    => '16',
            'height'   => '16',
        ],
        's_link'                      => [
            'position' => '139',
            'width'    => '16',
            'height'   => '16',
        ],
        's_lock'                      => [
            'position' => '140',
            'width'    => '16',
            'height'   => '16',
        ],
        's_loggoff'                   => [
            'position' => '141',
            'width'    => '16',
            'height'   => '16',
        ],
        's_notice'                    => [
            'position' => '142',
            'width'    => '16',
            'height'   => '16',
        ],
        's_okay'                      => [
            'position' => '143',
            'width'    => '16',
            'height'   => '16',
        ],
        's_passwd'                    => [
            'position' => '144',
            'width'    => '16',
            'height'   => '16',
        ],
        's_process'                   => [
            'position' => '145',
            'width'    => '16',
            'height'   => '16',
        ],
        's_really'                    => [
            'position' => '146',
            'width'    => '11',
            'height'   => '11',
        ],
        's_reload'                    => [
            'position' => '147',
            'width'    => '16',
            'height'   => '16',
        ],
        's_replication'               => [
            'position' => '148',
            'width'    => '16',
            'height'   => '16',
        ],
        's_rights'                    => [
            'position' => '149',
            'width'    => '16',
            'height'   => '16',
        ],
        's_sortable'                  => [
            'position' => '150',
            'width'    => '16',
            'height'   => '16',
        ],
        's_status'                    => [
            'position' => '151',
            'width'    => '16',
            'height'   => '16',
        ],
        's_success'                   => [
            'position' => '152',
            'width'    => '16',
            'height'   => '16',
        ],
        's_sync'                      => [
            'position' => '153',
            'width'    => '16',
            'height'   => '16',
        ],
        's_tbl'                       => [
            'position' => '154',
            'width'    => '16',
            'height'   => '16',
        ],
        's_theme'                     => [
            'position' => '155',
            'width'    => '16',
            'height'   => '16',
        ],
        's_top'                       => [
            'position' => '156',
            'width'    => '16',
            'height'   => '16',
        ],
        's_unlink'                    => [
            'position' => '157',
            'width'    => '16',
            'height'   => '16',
        ],
        's_vars'                      => [
            'position' => '158',
            'width'    => '16',
            'height'   => '16',
        ],
        's_views'                     => [
            'position' => '159',
            'width'    => '16',
            'height'   => '16',
        ],
        'window-new'                  => [
            'position' => '160',
            'width'    => '16',
            'height'   => '16',
        ],
    ];
}

?>
